name: photo_social
publish_to: "none"
version: 1.0.7+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^0.1.3
  get: ^3.22.2
  cached_network_image: ^2.4.1
  dio: ^3.0.10
  flutter_spinkit: ^4.1.2+1
  pull_to_refresh: ^1.6.3
  graphql_flutter: ^4.0.0-beta.5
  flutter_secure_storage: ^3.3.5
  bot_toast: ^3.0.5
  carousel_slider: ^2.3.1
  flutter_staggered_grid_view: ^0.3.2
  eva_icons_flutter: ^2.0.1
  timeago: ^2.0.29
  # image placeholder
  flutter_blurhash: ^0.5.0
  like_button: ^1.0.4
  photo_view: ^0.10.3
  #these package for update app
  package_info: ^0.4.3+2
  pub_semver: ^1.4.4
  flutter_downloader: ^1.5.0
  permission_handler: ^5.0.1+1
  #loading effect
  shimmer: ^1.1.2
  # launch app from url
  url_launcher: ^5.7.10
  # bottom bar
  google_nav_bar: ^3.1.0
  # persistent data
  hive: ^1.5.0-pre
  hive_flutter: ^0.3.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  pedantic: ^1.10.0-nullsafety

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSans-Regular
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
    - family: GoogleSans-Medium
      fonts:
        - asset: assets/fonts/GoogleSans-Medium.ttf
    - family: GoogleSans-Bold
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
    - family: GoogleSans-Italic
      fonts:
        - asset: assets/fonts/GoogleSans-Italic.ttf
    - family: GoogleSans-Bold-Italic
      fonts:
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
    - family: SocialIcon
      fonts:
        - asset: assets/custom/SocialIcon.ttf
