name: photo_social
publish_to: "none"
version: 1.0.7+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  pull_to_refresh: ^1.6.3
  graphql_flutter: ^5.0.0-nullsafety.2
  # not support windows
  #flutter_secure_storage: ^4.1.0
  bot_toast: ^4.0.1
  carousel_slider: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  eva_icons_flutter: ^3.0.0
  timeago: ^3.0.2
  # image placeholder
  flutter_blurhash: ^0.6.0
  like_button: ^2.0.2
  photo_view: ^0.11.1
  #these package for update app
  # not support windows, linux
  #package_info: ^2.0.0
  pub_semver: ^2.0.0
  flutter_downloader: ^1.5.0
  permission_handler: ^6.1.1

  # launch app from url
  url_launcher: ^6.0.3
  # bottom bar
  google_nav_bar: ^5.0.3
  # persistent data
  #hive: ^2.0.2
  #hive_flutter: ^1.0.0
  #sign in google
  google_sign_in: ^5.0.1
  flutter_svg: ^0.21.0-nullsafety.0
  path_provider: ^2.0.1
  beamer: ^1.0.0-nullsafety.9
  get_storage: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true

  assets:
    - assets/image/svgs/
    
  fonts:
    - family: GoogleSans-Regular
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
    - family: GoogleSans-Medium
      fonts:
        - asset: assets/fonts/GoogleSans-Medium.ttf
    - family: GoogleSans-Bold
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
    - family: GoogleSans-Italic
      fonts:
        - asset: assets/fonts/GoogleSans-Italic.ttf
    - family: GoogleSans-Bold-Italic
      fonts:
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
    - family: SocialIcon
      fonts:
        - asset: assets/custom/SocialIcon.ttf
